### ISSUE TITLE
Add a vignette

### ISSUE THREAD

**Issue by sckott** [ropensci/crminer#23]
This package needs more documentation!  Help out the community by contributing a vignette. If you don't know what a vignette is, check out http://r-pkgs.had.co.nz/vignettes.html for an introduction.  

If you aren't sure how to contribute on github checkout https://github.com/ropensci/crminer/blob/master/.github/CONTRIBUTING.md

Keep in mind our code of conduct https://github.com/ropensci/crminer/blob/master/CONDUCT.md

**Comment by zaynaib** [comment]
Hello,
I would like to help out on this issue. I am a r beginner but I do know Markdown very well.
Thanks,
Ola

**Comment by sckott** [comment]
Thanks for your interest @zaynaib - Follow tips here on how to make a vignette http://r-pkgs.had.co.nz/vignettes.html 

I've just pushed a blank file to make the vignette in: https://github.com/ropensci/crminer/blob/master/inst/vign/crminer-vignette.Rmd

let me know if you have any questions. 

This package may be a bit frustrating to run all examples in as some articles that functions in this package request require you to have access, typically through a university. But some examples will work if they request an article from an open access publisher.
