### ISSUE TITLE
PDFs from Wiley

### ISSUE THREAD

**Issue by simon-tarr** [ropensci/crminer#29]
Hello,

I'm trying to download a list of all journal articles from the Wiley journal 'Global Ecology & Biogeography' for some subsequent text mining analysis. My current aim is to download the PDFs for the DOIs. I believe I've managed to get a list of DOIs using the following code:

```
library(rcrossref)
library(crminer)
library(purrr)
library(dplyr)

geb_papers <- cr_works(filter = c(issn='1466-822X')) 

n_pages <- ceiling(geb_papers$meta$total_results / geb_papers$meta$items_per_page)

geb_dois<- map_dfr(1:n_pages, function(x) {
  # get the start record for the page
  strt <- (x - 1)*20 + 1
  dois <- cr_works(filter = c(issn='1466-8238'), offset = strt)$data %>% 
    filter(type == "journal-article")
  return(dois)
})

dois<-geb_dois$doi
```
So far, so good (I think). The next stage is to then use crm_links() on the list of DOIs like so:

`links<-lapply(dois, crm_links, type="pdf")
`

If I query the object `links` I notice that there is no PDF link for thie first item in the list. If we trace back the DOI for this article we get: 

```
dois[[1]]
[1] "10.1111/geb.12139"
```

Stick that DOI into a browser and you'll be taken to the article [here](https://onlinelibrary.wiley.com/doi/abs/10.1111/geb.12139). So there's something there and, in theory, should be downloadable, correct?

Any ideas what may be wrong? The above code should be reproducible so I was hoping some kind person would be able to spare 5 minutes to run it on a subset of the data (perhaps the first 10 entries to speed things up) to see whether they hit the same issue. Out of the first 20 elements in the list `links` I have 9 articles missing PDF links, which is quite a high percentage.

To confirm, I have an auth token for crossref in .Renviron, so I don't think it's an authentication issue. This is also backed up with the fact that the second element in `links` has a PDF link and can be downloaded when using `crm_pdf(links[[2]])`.

Thanks in advance!
Simon

**Comment by sckott** [comment]
thanks for this. edited it to make it reproducible, libraries weren't loaded

**Comment by sckott** [comment]
Please share the output of `sessionInfo()` when you have crminer loaded

**Comment by sckott** [comment]
If you look at Wiley links in Crossref's data http://api.crossref.org/members/311/works?filter=has-full-text:true they do not provide the type of article they are linking to - they only give "unspecified". So when using `crm_links` with Wiley I'd use `type="all"`. 

there's a parameter in `crm_pdf` `overwrite_unspecified` specifically to deal with Wiley's failure to give the format type, e.g., 

```r
crm_pdf(links[[1]], overwrite_unspecified=TRUE)
```

**Comment by simon-tarr** [comment]
> thanks for this. edited it to make it reproducible, libraries weren't loaded

Yes, sorry, forgot to copy the libraries at the top of my script! Thanks for adding them in.

> If you look at Wiley links in Crossref's data http://api.crossref.org/members/311/works?filter=has-full-text:true they do not provide the type of article they are linking to - they only give "unspecified". So when using `crm_links` with Wiley I'd use `type="all"`.
> 
> there's a parameter in `crm_pdf` `overwrite_unspecified` specifically to deal with Wiley's failure to give the format type, e.g.,
> 
> ```r
> crm_pdf(links[[1]], overwrite_unspecified=TRUE)
> ```

Thanks very much for explaining this and my apologies if I had missed this information in your tutorial. I've just tried with `crm_links(type="all")` followed by `crm_pdf(links[[1]], overwrite_unspecified=TRUE)` and it appears to have downloaded the original "missing" PDFs.

Thanks for your help,
Simon

**Comment by sckott** [comment]
glad it works. don't hesitate with any other questions.
