### ISSUE TITLE
Sage Journals

### ISSUE THREAD

**Issue by marley1** [ropensci/crminer#50]
Thank you for the library - its really great.

Does it allow the download of research papers from Sage Journals?

According to the Sage Journals Text and Data Mining policy, it is recommended to download articles through the CrossRef Text and Data Mining API.

I was therefore hoping to pass the DOI for papers from SAGE Journals, but unsure if/how to insert or obtain an authentication token?

Kind Regards

**Comment by sckott** [comment]
thanks for your question. 

I've asked in the crossref forum about Sage https://community.crossref.org/t/tdm-click-through-service-sage-any-updates/1361 

As far as I can tell Sage isn't involved in the so called Click through service, so I don't think token's from that service will do any good, but I've asked in that forum link above. 

you can try to get Sage articles, for example:

```r
library(rcrossref)
library(crminer)

# get some Sage DOIs
# Sage Crossref member number is 179
sage <- cr_members(179, works = TRUE)
sage_dois <- sage$data$doi

# get links
links <- lapply(sage_dois[1:10], crm_links)

# try to get articles
# some may work, some may not work, depending on your access
crm_pdf(links[[1]])
crm_pdf(links[[3]])
crm_pdf(links[[5]])
crm_pdf(links[[10]])

# if it works, you can index to text
x <- crm_pdf(links[[10]]) 
x$text
```

Access for Sage is most likely just IP address based, so if you're on an IP address that gives you access to Y paper, then you get that paper, if not, then they'll reject the request

**Comment by marley1** [comment]
Thanks so much for your response and follow up.

I'm using my institution IP address, and have used your example and am able to obtain full text content from SAGE journal articles.

Thanks once again
